### ISSUE TITLE
Additionally trained pretrained network yields bad results. 

### ISSUE THREAD

**Issue by Lait-au-Cafe** [shepnerd/outpainting_srn#10]
I'm planning to use this network for other domain and I'm trying to train the network by myself with train.py. 
First of all, in order to clarify whether my way of training is correct, I proceeded training starting from pretrained checkpoint of CelebA which you provide in Google Drive, using CelebA dataset. 
Here, I expected the results of test.py don't drastically change because I thought the provided 
pretrained checkpoint was well converged one. 
However, additionally trained network yielded bad results. 
I think some parameters need to be tuned but I'm not sure how to fix this.  

Dataset: 
Acquired from the CelebA homepage (http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html). 
dataset/CelebA/Img/img_align_celeba.zip at the GoogleDrive (https://drive.google.com/drive/folders/0B7EVK8r0v71pWEZsZE9oNnFzTm8)

Commands: 

```
$ python train.py --dataset celebahq-256 --data_file ~/projects/resize/celeba_train.txt --gpu_ids 0,1 --pretrain_network 0 --batch_size 8 --load_model_dir ./checkpoints/celebahq-srn-subpixel/
$ python test.py --dataset celebahq-256 --data_file ./imgs/celebahq-256/ --load_model_dir ./checkpoints/20200607-200756_celebahq-256_srn_subpixel_contextual_b8_s256x256_gc64_dc64_rand-mask/ --random_mask 1
```

Result

![outpaint](https://user-images.githubusercontent.com/29175977/84000534-cea47500-a99f-11ea-8724-05cd8a2069eb.png)

**Comment by shepnerd** [comment]
The given face extrapolation model is trained on [CelebA-HQ](https://drive.google.com/drive/folders/1_BsFYYGVvcjcPNhPam2STBDFG3eKAdKr) (256x256) instead of the original celeba. Using the testing images from celeba as inputs to your trained model on celeba should yield reasonable results. 

P.S. The train/test splits of CelebA-HQ are given in [train_shuffled.txt](https://github.com/shepnerd/outpainting_srn/files/4745077/train_shuffled.txt) and [val_shuffled.txt](https://github.com/shepnerd/outpainting_srn/files/4745076/val_shuffled.txt).
